
set(LIBRARY_PROJECT_NAME "Core-24")
set(LIBRARY_NAME "core-lang")
set(LIBRARY_VERSION "0.0.1")
set(LIBRARY_FULL_VERSION "0.0.1-SNAPSHOT")
set(LIBRARY_TYPE "SHARED")
set(LIBRARY_DESCRIPTION "")
set(LIBRARY_INSTALL_DIR "")
set(LIBRARY_SOURCE_DIR ${PROJECT_SOURCE_DIR})

set(LIBRARY_CMAKE_VERSION "3.10")

set(LIBRARY_CXX_VERSION 20)
set(LIBRARY_CXX_OPTIONS "")
set(LIBRARY_CXX_REQUIRED ON)
set(LIBRARY_EXPORT_COMMANDS ON)

set(LIBRARY_BUILD_TEST ON)
set(LIBRARY_BUILD_SRC ON)
set(LIBRARY_BUILD_LIB ON)

set(LIBRARY_PLATFORM "")


