include("../../Config.cmake")

set(TEST_PROJECT_NAME "Core-24")
set(TEST_NAME "AllTests")
set(TEST_VERSION "0.0.1-SNAPSHOT")
set(TEST_DESCRIPTION "")
set(TEST_INSTALL_DIR "")
set(TEST_SOURCE_DIR ${PROJECT_SOURCE_DIR})

set(TEST_CXX_VERSION 11)
set(TEST_CXX_OPTIONS "")
set(TEST_CXX_REQUIRED ON)
set(TEST_EXPORT_COMMANDS ON)

set(TEST_PLATFORM "")